spring.application.name=FindMoviesAI

# Configuração da OMDb API injetada a partir do .env
omdb.api.url=${OMDB_API_URL:http://www.omdbapi.com/}
omdb.api.key=${OMDB_API_KEY:b3115e8d}

# Configuração do Ollama local
spring.ai.ollama.base-url=${OLLAMA_LOCAL_URL:http://localhost:11434}
spring.ai.ollama.chat.model=llama3.1
spring.ai.ollama.chat.options.temperature=0.4

# Desabilitando a autoconfiguração do ChromaDB pois ele não está rodando localmente no momento
spring.autoconfigure.exclude=org.springframework.ai.vectorstore.chroma.autoconfigure.ChromaVectorStoreAutoConfiguration
